# Generated by Django 5.0 on 2023-12-22 05:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='adhar_card_no',
            field=models.CharField(default='1234567890', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+918888888888', max_length=128, region='IN'),
            preserve_default=False,
        ),
    ]
